/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2021-01-27 20:14:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.sygealoc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import supernova.pfe.tool.MySession;
import java.net.NetworkInterface;
import java.net.InetAddress;

public final class connexion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/sygealoc/part/lastpart.jsp", Long.valueOf(1611778458000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.InetAddress");
    _jspx_imports_classes.add("supernova.pfe.tool.MySession");
    _jspx_imports_classes.add("java.net.NetworkInterface");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    MySession.path = (request.getServletContext().getRealPath("/").replace("\\", "/").replace("build/", "")) + "assets";
    new MySession(request);
    if (MySession.getModuleFor(MySession.mac) != null && request.getSession().getAttribute("member_info") == null) {
        response.sendRedirect("verouiller");
    }
    
    if (request.getSession().getAttribute("company") == null) {
        response.sendRedirect("erreur");
    }

      out.write("\n");
      out.write("\n");
      out.write("<html class=\"loading\" lang=\"en\" data-textdirection=\"ltr\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\n");
      out.write("        <meta name=\"description\" content=\"Systeme de gestion de location de voiture\">\n");
      out.write("        <meta name=\"keywords\" content=\"avis, rental, car, haiti, supernova, chcl, pfe, ueh\">\n");
      out.write("        <meta name=\"author\" content=\"SUPERNOVA\">\n");
      out.write("        <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu==null?'DASHBOARD':active_menu.toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap-extended.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/components.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/extensions/toastr.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/line-awesome/css/line-awesome.min.css\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.getLOGO()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body style=\"background-color: white\" class=\"vertical-layout vertical-menu-modern 1-column blank-page\" data-menu=\"vertical-menu-modern\" data-col=\"1-column\">\n");
      out.write("        <div class=\"app-content content\">\n");
      out.write("            <div class=\"content-overlay\"></div>\n");
      out.write("            <div class=\"content-wrapper\">\n");
      out.write("                <div class=\"content-header row\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"content-body\">\n");
      out.write("                    <section class=\"row flexbox-container\">\n");
      out.write("                        <div class=\"col-12 d-flex align-items-center justify-content-center card-img-top img-fluid bg-cover height-300 huser-profile-cover-image\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/uploads/car/19.jpg')\">\n");
      out.write("                            <div class=\"col-lg-4 col-md-8 col-10 box-shadow-2 p-0\">\n");
      out.write("                                <div class=\"card border-grey border-lighten-3 m-0\">\n");
      out.write("                                    <div class=\"card-header border-0\">\n");
      out.write("                                        <div class=\"card-title text-center\">\n");
      out.write("                                            <div class=\"p-1\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.getLOGO()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"branding logo\"></div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <h5 class=\"card-subtitle line-on-side text-muted text-center font-small-8 pt-3 text-bold-800\"><span>CONNEXION &Agrave; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME().toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                                        </h5>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"card-content\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            <form class=\"form-horizontal form-simple\" action=\"connexion\" method=\"post\">\n");
      out.write("                                                <fieldset class=\"form-group position-relative has-icon-left mb-0\">\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" name=\"pseudo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pseudo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Pseudo\">\n");
      out.write("                                                    <div class=\"form-control-position\">\n");
      out.write("                                                        <i class=\"la la-user\"></i>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </fieldset>\n");
      out.write("\n");
      out.write("                                                <fieldset class=\"form-group position-relative has-icon-left\">\n");
      out.write("                                                    <input type=\"password\" class=\"form-control\" name=\"password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Mot de passe\">\n");
      out.write("                                                    <div class=\"form-control-position\">\n");
      out.write("                                                        <i class=\"la la-key\"></i>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </fieldset>\n");
      out.write("                                                <button name=\"action\" type=\"submit\" class=\"btn btn-info btn-block\"><i class=\"ft-unlock\"></i> Connecter</button>\n");
      out.write("                                            </form>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"sidenav-overlay\"></div>\n");
      out.write("<div class=\"drag-target\"></div>\n");
      out.write("\n");
      out.write("<footer id=\"footerview\" class=\"footer footer-static footer-light navbar-border navbar-shadow\">\n");
      out.write("    <p class=\"clearfix blue-grey lighten-2 text-sm-center mb-0 px-2\">\n");
      out.write("        <span class=\"float-md-left d-block d-md-inline-block\">\n");
      out.write("            Copyright &copy; 2021 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        </span>\n");
      out.write("        <span class=\"float-md-right d-none d-lg-block\">\n");
      out.write("            chcuehl.pfe.supernova\n");
      out.write("            <span id=\"scroll-top\"></span>\n");
      out.write("        </span>\n");
      out.write("    </p>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"confirmdisconnection\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel1\"\n");
      out.write("     aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <section class=\"contact-form\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel1\">Deconnexion</h5>\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <span id=\"del_id\" style=\"display: none\"></span>\n");
      out.write("                    <p>Etes vous sur de vouloir vous deconnecter ?</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <fieldset class=\"form-group position-relative has-icon-left mb-0\">\n");
      out.write("                        <button onclick=\"disconnect()\" type=\"button\" class=\"btn btn-info add-contact-item\"><i\n");
      out.write("                                class=\"la la-paper-plane-o d-block d-lg-none\"></i> <span class=\"d-none d-lg-block\">Oui</span></button>\n");
      out.write("                    </fieldset>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/js/vendors.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/core/app-menu.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/core/app.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/scripts/customizer.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/scripts/footer.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/mask.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/datatable.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("                            function numberMask(inputid, limit) {\n");
      out.write("                                return IMask(\n");
      out.write("                                        document.getElementById(inputid),\n");
      out.write("                                        {\n");
      out.write("                                            mask: '$ num',\n");
      out.write("                                            blocks: {\n");
      out.write("                                                num: {\n");
      out.write("                                                    mask: Number,\n");
      out.write("                                                    thousandsSeparator: ' ',\n");
      out.write("                                                    min: 1,\n");
      out.write("                                                    max: limit\n");
      out.write("                                                }\n");
      out.write("                                            }\n");
      out.write("                                        }\n");
      out.write("                                );\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function readable(nbr){\n");
      out.write("                                var nombre = '' + nbr;\n");
      out.write("                                var retour = '';\n");
      out.write("                                var count = 0;\n");
      out.write("                                for (var i = nombre.length - 1; i >= 0; i--)\n");
      out.write("                                {\n");
      out.write("                                    if (count != 0 && count % 3 == 0)\n");
      out.write("                                        retour = nombre[i] + ' ' + retour;\n");
      out.write("                                    else\n");
      out.write("                                        retour = nombre[i] + retour;\n");
      out.write("                                    count++;\n");
      out.write("                                }\n");
      out.write("                                return retour;\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function disconnect() {\n");
      out.write("                                window.location.href = \"deconnexion\";\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" != null && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length > 0) {\n");
      out.write("                                $(\"#tableaudebord\").attr(\"class\", $(\"#tableaudebord\").attr(\"class\").replace(\" active\", \"\"));\n");
      out.write("                                $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\", $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\") + \" active\");\n");
      out.write("                            } else {\n");
      out.write("                                $(\"#tableaudebord\").attr(\"class\", $(\"#tableaudebord\").attr(\"class\") + \" active\");\n");
      out.write("                                $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\", $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\").replace(\" active\", \"\"));\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function resetData() {\n");
      out.write("                                $(\"#add_form\")[0].reset();\n");
      out.write("                                $(\"#edit_form\")[0].reset();\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function holdModal(id) {\n");
      out.write("                                $(\"#\" + id).modal({\n");
      out.write("                                    keyboard: false,\n");
      out.write("                                    backdrop: 'static'\n");
      out.write("                                }).show();\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function removeSession(parameter) {\n");
      out.write("                                $.ajax({\n");
      out.write("                                    url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/services/removeSession.jsp',\n");
      out.write("                                    type: \"POST\",\n");
      out.write("                                    data: {parameter: parameter},\n");
      out.write("                                    dataType: 'json',\n");
      out.write("                                    success: function (data) {\n");
      out.write("                                    },\n");
      out.write("                                    error: function (data) {\n");
      out.write("                                        toastr.error(data.message, \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME().toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu.toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \");\n");
      out.write("                                    }\n");
      out.write("                                });\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/js/extensions/toastr.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length > 0) {\n");
      out.write("        toastr.error(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME().toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu.toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \");\n");
      out.write("    }\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
