/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2021-01-30 20:51:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.sygealoc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import supernova.pfe.dao.D_Vehicule;
import supernova.pfe.model.Vehicule;
import supernova.pfe.dao.D_Location;
import supernova.pfe.model.Location;
import supernova.pfe.dao.D_Auth;
import supernova.pfe.tool.Db_access;
import supernova.pfe.tool.MyDate;
import supernova.pfe.model.UserPermission;
import supernova.pfe.model.UserPermission;
import supernova.pfe.model.UserPermission;
import supernova.pfe.model.UserPermission;
import java.util.ArrayList;
import supernova.pfe.model.Employe;
import supernova.pfe.model.Localization;
import supernova.pfe.tool.MySession;
import supernova.pfe.tool.Db_access;

public final class tableaudebord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/sygealoc/part/lastpart.jsp", Long.valueOf(1611778458000L));
    _jspx_dependants.put("/WEB-INF/sygealoc/part/firstpart.jsp", Long.valueOf(1611778458000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1611778540000L));
    _jspx_dependants.put("jar:file:/C:/Users/NHELTECH/Desktop/pfe.supernova/apache-tomcat/webapps/sygealoc%23%231.0/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343837818000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("supernova.pfe.model.UserPermission");
    _jspx_imports_classes.add("supernova.pfe.model.Localization");
    _jspx_imports_classes.add("supernova.pfe.dao.D_Location");
    _jspx_imports_classes.add("supernova.pfe.tool.MySession");
    _jspx_imports_classes.add("supernova.pfe.dao.D_Auth");
    _jspx_imports_classes.add("supernova.pfe.model.Employe");
    _jspx_imports_classes.add("supernova.pfe.tool.MyDate");
    _jspx_imports_classes.add("supernova.pfe.model.Vehicule");
    _jspx_imports_classes.add("supernova.pfe.dao.D_Vehicule");
    _jspx_imports_classes.add("supernova.pfe.model.Location");
    _jspx_imports_classes.add("supernova.pfe.tool.Db_access");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    if (request.getSession().getAttribute("company") == null) {
        response.sendRedirect("erreur");
    }
    
    MySession.path = (request.getServletContext().getRealPath("/").replace("\\", "/").replace("build/", ""))+"assets";
    new MySession(request);
    
    int total_pages = Integer.parseInt(request.getAttribute("total_pages") != null ? request.getAttribute("total_pages").toString() : "1");
    int nbbypage = Integer.parseInt(request.getAttribute("nbbypage") != null ? request.getAttribute("nbbypage").toString() : "0");;
    int active_page = Integer.parseInt(request.getAttribute("active_page") != null ? request.getAttribute("active_page").toString() : "0");
    Employe m = null;
    ArrayList<UserPermission> r = null;
    if (request.getSession() == null || request.getSession().getAttribute("member_info") == null) {
//        response.sendRedirect("connexion");
    } else {
        m = ((Employe) request.getSession().getAttribute("member_info"));
        r = ((ArrayList<UserPermission>) request.getSession().getAttribute("rights"));
        
        if (request.getAttribute("position") != null) {
            if(!request.getAttribute("position").equals("impression")){ 
                MySession.setPosition(m.PSEUDO(), request.getAttribute("position").toString());   
            }
        }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"loading\" lang=\"en\" data-textdirection=\"ltr\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html\" charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\n");
      out.write("        <meta name=\"description\" content=\"Systeme de gestion de location de voiture\">\n");
      out.write("        <meta name=\"keywords\" content=\"avis, rental, car, haiti, supernova, chcl, pfe, ueh\">\n");
      out.write("        <meta name=\"author\" content=\"SUPERNOVA\">\n");
      out.write("        <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu==null?'TABLEAU DE BORD':active_menu.toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company!=null?'-':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/ico/apple-icon-120.png\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.getLOGO()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap-extended.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/colors.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/components.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/core/menu/menu-types/vertical-menu-modern.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/core/colors/palette-gradient.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/charts/jquery-jvectormap-2.0.3.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/charts/morris.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/plugins/extensions/toastr.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/extensions/toastr.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/core/colors/palette-gradient.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/fonts.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/line-awesome/css/line-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/feather/style.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/simple-line-icons/css/simple-line-icons.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/meteocons/style.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/font-awesome/css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/fonts/material-design-icons/material-icon.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap-extended.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/colors.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/components.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/vendors.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/pickers/daterange/daterangepicker.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/pickers/pickadate/pickadate.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/core/menu/menu-types/vertical-menu-modern.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/core/colors/palette-gradient.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/plugins/pickers/daterange/daterange.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/css/extensions/toastr.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/datatable.css\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body class=\"vertical-layout vertical-menu-modern 2-columns fixed-navbar\" data-open=\"click\" data-menu=\"vertical-menu-modern\" data-col=\"2-columns\">\n");
      out.write("        <nav class=\"header-navbar navbar-expand-lg navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-dark navbar-shadow\">\n");
      out.write("            <div class=\"navbar-wrapper\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <ul class=\"nav navbar-nav flex-row\">\n");
      out.write("                        <li class=\"nav-item mobile-menu d-lg-none mr-auto\"><a class=\"nav-link nav-menu-main menu-toggle hidden-xs\" href=\"#\"><i class=\"ft-menu font-large-1\"></i></a></li>\n");
      out.write("                        <li class=\"nav-item mr-auto\"><a class=\"navbar-brand\" href=\"tableaudebord\"><img class=\"brand-logo\" alt=\"sygealoc logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.getLOGO()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                                <h3 class=\"brand-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3></a></li>\n");
      out.write("                        <li class=\"nav-item d-none d-lg-block nav-toggle\"><a class=\"nav-link modern-nav-toggle pr-0\" data-toggle=\"collapse\"><i class=\"toggle-icon ft-toggle-right font-medium-3 white\" data-ticon=\"ft-toggle-right\"></i></a></li>\n");
      out.write("                        <li class=\"nav-item d-lg-none\"><a class=\"nav-link open-navbar-container\" data-toggle=\"collapse\" data-target=\"#navbar-mobile\"><i class=\"la la-ellipsis-v\"></i></a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"navbar-container content\">\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbar-mobile\">\n");
      out.write("                        <ul class=\"nav navbar-nav mr-auto float-left\">\n");
      out.write("                            <li class=\"nav-item d-none d-lg-block text-bold-500\" >\n");
      out.write("                                AVIS RENT A CAR\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                        <ul class=\"nav navbar-nav float-right\">\n");
      out.write("                            <li class=\"dropdown dropdown-user nav-item\"><a class=\"dropdown-toggle nav-link dropdown-user-link\" href=\"#\" data-toggle=\"dropdown\"><span class=\"mr-1 user-name text-bold-700\">");
      out.print(m.PSEUDO());
      out.write("</span><span class=\"avatar avatar-online\"><img height=\"20px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/uploads/utilisateur/admin920313mon.jpg\" alt=\"avatar\"><i></i></span></a>\n");
      out.write("                                <div class=\"dropdown-menu dropdown-menu-right\">\n");
      out.write("                                    <a class=\"dropdown-item\" id=\"prof_link\" href=\"profile\"><i class=\"ft-user\"></i> Profile</a>\n");
      out.write("                                    <div class=\"dropdown-divider\"></div><a class=\"dropdown-item\" href=\"#\" onclick=\"holdModal('confirmdisconnection')\"><i class=\"ft-power\"></i> D&eacute;connexion</a>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <div class=\"main-menu menu-fixed menu-dark menu-accordion menu-shadow\" data-scroll-to-active=\"true\">\n");
      out.write("            <div class=\"main-menu-content\">\n");
      out.write("                <ul class=\"navigation navigation-main\" id=\"main-menu-navigation\" data-menu=\"menu-navigation\">\n");
      out.write("                    <li class=\" navigation-header\"><span data-i18n=\"Admin Panels\">Acceuil</span><i class=\"la la-ellipsis-h\" data-toggle=\"tooltip\" data-placement=\"right\" data-original-title=\"Admin Panels\"></i>\n");
      out.write("                    <li class=\"nav-item\" id=\"tableaudebord\"><a href=\"tableaudebord\"><i class=\"la la-home\"></i><span class=\"menu-title\" data-i18n=\"Dashboard\">Tableau de bord</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
if ((r != null) && ((r.get(0).getCAN_VIEW() == 1) || (r.get(1).getCAN_VIEW() == 1)
                                || (r.get(2).getCAN_VIEW() == 1) || (r.get(3).getCAN_VIEW() == 1)
                                || (r.get(4).getCAN_VIEW() == 1) || (r.get(5).getCAN_VIEW() == 1))) {
      out.write("\n");
      out.write("                    <li class=\" navigation-header\"><span data-i18n=\"Admin Panels\">Gestion</span><i class=\"la la-ellipsis-h\" data-toggle=\"tooltip\" data-placement=\"right\" data-original-title=\"Admin Panels\"></i>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(0).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" nav-item\" id=\"employe\"><a href=\"employe\"><i class=\"la la-user\"></i><span class=\"menu-title\" data-i18n=\"employe\">Employ&eacute;</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(1).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" nav-item\" id=\"client\"><a href=\"client\"><i class=\"las la-clone\"></i><span class=\"menu-title\" data-i18n=\"client\">Client</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(2).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" nav-item\" id=\"fournisseur\"><a href=\"fournisseur\"><i class=\"las la-industry\"></i><span class=\"menu-title\" data-i18n=\"fournisseur\">Fournisseur</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(3).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" nav-item\" id=\"stock\"><a href=\"stock\"><i class=\"la la-automobile\"></i><span class=\"menu-title\" data-i18n=\"stock\">Stock</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(4).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" nav-item\" id=\"reservation\"><a href=\"reservation\"><i class=\"las la-money-bill-wave-alt\"></i></i><span class=\"menu-title\" data-i18n=\"reservation\">R&eacute;servation</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(5).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" nav-item\" id=\"location\"><a href=\"location\"><i class=\"las la-hand-holding-usd\"></i><span class=\"menu-title\" data-i18n=\"location\">Location</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("\n");
      out.write("                    ");
if (r != null && r.get(6).getCAN_VIEW() == 1) {
      out.write("\n");
      out.write("                    <li class=\" navigation-header\"><span data-i18n=\"Securite\">Securite</span><i class=\"la la-ellipsis-h\" data-toggle=\"tooltip\" data-placement=\"right\" data-original-title=\"Admin Panels\"></i>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\" nav-item\" id=\"utilisateur\"><a href=\"utilisateur\"><i class=\"la la-users\"></i><span class=\"menu-title\" data-i18n=\"utilisateur\">Utilisateur</span></a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"app-content content\">\n");
      out.write("            <div class=\"content-overlay\"></div>\n");
      out.write("            <div class=\"content-wrapper\">\n");
      out.write("                <div class=\"content-header row\">\n");
      out.write("                    <div class=\"content-header-left col-md-6 col-12 mb-2 breadcrumb-new\">\n");
      out.write("                        <h3 class=\"content-header-title mb-0 d-inline-block\" id=\"currentpage\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu==null?\"TABLEAU DE BORD\":active_menu.toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("                        <div class=\"row breadcrumbs-top d-inline-block\">\n");
      out.write("                            <div class=\"breadcrumb-wrapper col-12\">\n");
      out.write("                                <ol class=\"breadcrumb\">\n");
      out.write("                                    <li class=\"breadcrumb-item\"><a href=\"tableaudebord\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME().toLowerCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"breadcrumb-item\"><a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu==null?\"acceuil\":(active_menu==\"utilisateur\" || active_menu==\"parametre\"?\"securite\":\"gestion\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"breadcrumb-item active\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu==null?\"Tableau de bord\":active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                    </li>\n");
      out.write("                                </ol>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                ");
}
      out.write('\n');
      out.write('\n');
  
    if(m!=null && m.PSEUDO()!=null){
        MySession.setPosition(m.PSEUDO(), "tableaudebord");   
    }    
    ArrayList<Vehicule> v = new D_Vehicule().get();
    int nbemployee = new D_Auth().get().size();
    int nbuser = new D_Auth().getUsers().size();
    int pfu = (nbemployee / nbuser) * 100;
    int pfp = 100 - pfu;
    int nbloc = new D_Auth().getTotalFrom("location");
    int nbclient = new D_Auth().getTotalFrom("client");
    int nbfournisseur = new D_Auth().getTotalFrom("fournisseur");
    int nblate = 0;
    int nbprogress = 0;
    int nbrepar = 0;
    int nbveh = 0;

    for (Location lc : new D_Location().get()) {
        if (!lc.ETAT().equals("Actif")) {
            nblate++;
        } else {
            nbprogress++;
        }
    }
    int nbvfree = 0;
    for (Vehicule ve : v) {
        if (ve.ETAT().equals("En reparation")) {
            nbrepar++;
        }
        nbveh++;
        if (ve.ETAT().equals("Libre")) {
            nbvfree++;
        }
    }
    int pve = (nblate * 100) / (nbveh==0?1:nbveh);
    int pvrepar = (nbrepar * 100) / (nbveh==0?1:nbveh);
    int pvfree = (nbvfree * 100) / (nbveh==0?1:nbveh);
    int pvprogress = (nbprogress * 100) / (nbloc==0?1:nbloc);

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"content-body\"><!-- Revenue, Hit Rate & Deals -->\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-xl-6 col-12\">\n");
      out.write("            <div class=\"card\" style=\"display:none\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h4 class=\"card-title\">Statistiques</h4>\n");
      out.write("                    <a class=\"heading-elements-toggle\"><i class=\"la la-ellipsis-v font-medium-3\"></i></a>\n");
      out.write("                    <div class=\"heading-elements\">\n");
      out.write("                        <ul class=\"list-inline mb-0\">\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-content collapse show\" >\n");
      out.write("                    <div class=\"card-body pt-0\">\n");
      out.write("                        <div class=\"chartjs\">\n");
      out.write("                            <canvas id=\"thisYearRevenue\" width=\"400\" class=\"position-absolute\"></canvas>\n");
      out.write("                            <canvas id=\"lastYearRevenue\" width=\"400\"></canvas>\n");
      out.write("                        </div>\n");
      out.write("                    </div>                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card\" height=\"400\">\n");
      out.write("                <div class=\"card-content\">\n");
      out.write("                    <div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("                        <ol class=\"carousel-indicators\">\n");
      out.write("                            <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                            <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\n");
      out.write("                            <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\n");
      out.write("                            <li data-target=\"#carousel-example-generic\" data-slide-to=\"3\"></li>\n");
      out.write("                            <li data-target=\"#carousel-example-generic\" data-slide-to=\"4\"></li>\n");
      out.write("                        </ol>\n");
      out.write("                        \n");
      out.write("                        <div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("                            <div class=\"carousel-item active\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/carousel/01.jpg\" class=\"d-block w-100\" alt=\"First slide\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"carousel-item\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/carousel/02.jpg\" class=\"d-block w-100\" alt=\"Second slide\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"carousel-item\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/carousel/03.jpg\" class=\"d-block w-100\" alt=\"Third slide\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"carousel-item\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/carousel/04.jpg\" class=\"d-block w-100\" alt=\"Fourth slide\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"carousel-item\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/carousel/05.jpg\" class=\"d-block w-100\" alt=\"Fifth slide\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                            \n");
      out.write("                        <a class=\"carousel-control-prev\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                            <span class=\"la la-angle-left\" aria-hidden=\"true\"></span>\n");
      out.write("                            <span class=\"sr-only\">Previous</span>\n");
      out.write("                        </a>\n");
      out.write("                        <a class=\"carousel-control-next\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\n");
      out.write("                            <span class=\"la la-angle-right icon-next\" aria-hidden=\"true\"></span>\n");
      out.write("                            <span class=\"sr-only\">Next</span>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-xl-6 col-12\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 col-12\">\n");
      out.write("                    <div class=\"card pull-up\">\n");
      out.write("                        <div class=\"card-header bg-hexagons\">\n");
      out.write("                            <h4 class=\"card-title\">Chart concernant le pourcentage de la location des vehicules</h4>\n");
      out.write("                            <a class=\"heading-elements-toggle\"><i class=\"la la-ellipsis-v font-medium-3\"></i></a>\n");
      out.write("                            <div class=\"heading-elements\">\n");
      out.write("                                <ul class=\"list-inline mb-0\">\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"card-content collapse show bg-hexagons\">\n");
      out.write("                            <div class=\"card-body pt-0\">\n");
      out.write("                                <div class=\"chartjs\">\n");
      out.write("                                    <canvas id=\"hit-rate-doughnut\" height=\"275\"></canvas>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 col-12\">\n");
      out.write("                    <div class=\"card pull-up\">\n");
      out.write("                        <div class=\"card-content collapse show bg-gradient-directional-danger\">\n");
      out.write("                            <div class=\"card-body bg-hexagons-daner\">\n");
      out.write("                                <h4 class=\"card-title white\">Chart concernant le pourcentage de l'etat du nombre de locations\n");
      out.write("                                </h4>\n");
      out.write("                                <div class=\"chartjs\">\n");
      out.write("                                    <canvas id=\"deals-doughnut\" height=\"275\"></canvas>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-6 col-12\">\n");
      out.write("                    <div class=\"card pull-up\">\n");
      out.write("                        <div class=\"card-content\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <div class=\"media d-flex\">\n");
      out.write("                                    <div class=\"media-body text-left\">\n");
      out.write("                                        <h6 class=\"text-muted\">Les locations </h6>\n");
      out.write("                                        <h3>");
      out.print(nbloc < 10 ? "0" + nbloc : nbloc);
      out.write("</h3>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"align-self-center\">\n");
      out.write("                                        <i class=\"icon-trophy success font-large-2 float-right\"></i>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-6 col-12\">\n");
      out.write("                    <div class=\"card pull-up\">\n");
      out.write("                        <div class=\"card-content\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <div class=\"media d-flex\">\n");
      out.write("                                    <div class=\"media-body text-left\">\n");
      out.write("                                        <h6 class=\"text-muted\">Les clients</h6>\n");
      out.write("                                        <h3>");
      out.print(nbclient < 10 ? "0" + nbclient : nbclient);
      out.write("</h3>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"align-self-center\">\n");
      out.write("                                        <i class=\"icon-call-in danger font-large-2 float-right\"></i>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-12 col-md-3\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h4 class=\"card-title\">Location & Vehicule</h4>\n");
      out.write("                    <a class=\"heading-elements-toggle\"><i class=\"la la-ellipsis-v font-medium-3\"></i></a>\n");
      out.write("                    <div class=\"heading-elements\">\n");
      out.write("                        <ul class=\"list-inline mb-0\">\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-content collapse show\">\n");
      out.write("                    <div class=\"card-body pt-0\">\n");
      out.write("                        <p>En retard/annulee <span class=\"float-right text-bold-600\">");
      out.print(nblate < 10 ? "0" + nblate : nblate);
      out.write("</span></p>\n");
      out.write("                        <div class=\"progress progress-sm mt-1 mb-0 box-shadow-1\">\n");
      out.write("                            <div class=\"progress-bar bg-gradient-x-danger\" role=\"progressbar\" style=\"width: ");
      out.print(pve);
      out.write("%\" aria-valuenow=\"");
      out.print(pve);
      out.write("%\"\n");
      out.write("                                 aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div>\n");
      out.write("                        <p class=\"pt-1\">Vehicule en reparation <span class=\"float-right\"><span class=\"text-bold-600\">");
      out.print(nbrepar < 10 ? "0" + nbrepar : nbrepar);
      out.write("</span></span>\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"progress progress-sm mt-1 mb-0 box-shadow-1\">\n");
      out.write("                            <div class=\"progress-bar bg-gradient-x-success\" role=\"progressbar\" style=\"width: ");
      out.print(pvrepar);
      out.write("%\" aria-valuenow=\"");
      out.print(pvrepar);
      out.write("\"\n");
      out.write("                                 aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-12 col-md-3\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h4 class=\"card-title\">Vehicule & Details</h4>\n");
      out.write("                    <div class=\"heading-elements\">\n");
      out.write("                        <ul class=\"list-inline mb-0\">\n");
      out.write("                            <li><a href=\"stock\">voir</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-content collapse show\">\n");
      out.write("                    <div class=\"card-body p-0\">\n");
      out.write("                        <div class=\"table-responsive\">\n");
      out.write("                            <table class=\"table mb-0\">\n");
      out.write("                                <tbody>\n");
      out.write("                                    ");
 int i = 0;
                                        for (Vehicule vc : v) {
                                            i++;
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th scope=\"row\" class=\"");
      out.print((i == 1) ? "border-top-0" : "");
      out.write('"');
      out.write('>');
      out.print(vc.MARQUE());
      out.write("</th>\n");
      out.write("                                        <td class=\"");
      out.print((i == 1) ? "border-top-0" : "");
      out.write(" text-right\">");
      out.print(vc.NUMPLAQUE());
      out.write("</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    ");
 if (i == 3) {
                                                break;
                                            }
                                        }
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-12 col-md-6\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h4 class=\"card-title text-center\">Personnel & Utilisateur</h4>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-content collapse show\">\n");
      out.write("                    <div class=\"card-body pt-0\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-6 col-12 border-right-blue-grey border-right-lighten-5 text-center\">\n");
      out.write("                                <h4 class=\"font-large-2 text-bold-400\">");
      out.print(nbemployee < 10 ? "0" + nbemployee : nbemployee);
      out.write("</h4>\n");
      out.write("                                <p class=\"blue-grey lighten-2 mb-0\">Personnel</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6 col-12 text-center\">\n");
      out.write("                                <h4 class=\"font-large-2 text-bold-400\">");
      out.print(nbuser < 10 ? "0" + nbuser : nbuser);
      out.write("</h4>\n");
      out.write("                                <p class=\"blue-grey lighten-2 mb-0\">Utilisateur</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"sidenav-overlay\"></div>\n");
      out.write("<div class=\"drag-target\"></div>\n");
      out.write("\n");
      out.write("<footer id=\"footerview\" class=\"footer footer-static footer-light navbar-border navbar-shadow\">\n");
      out.write("    <p class=\"clearfix blue-grey lighten-2 text-sm-center mb-0 px-2\">\n");
      out.write("        <span class=\"float-md-left d-block d-md-inline-block\">\n");
      out.write("            Copyright &copy; 2021 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        </span>\n");
      out.write("        <span class=\"float-md-right d-none d-lg-block\">\n");
      out.write("            chcuehl.pfe.supernova\n");
      out.write("            <span id=\"scroll-top\"></span>\n");
      out.write("        </span>\n");
      out.write("    </p>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"confirmdisconnection\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel1\"\n");
      out.write("     aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <section class=\"contact-form\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel1\">Deconnexion</h5>\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <span id=\"del_id\" style=\"display: none\"></span>\n");
      out.write("                    <p>Etes vous sur de vouloir vous deconnecter ?</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <fieldset class=\"form-group position-relative has-icon-left mb-0\">\n");
      out.write("                        <button onclick=\"disconnect()\" type=\"button\" class=\"btn btn-info add-contact-item\"><i\n");
      out.write("                                class=\"la la-paper-plane-o d-block d-lg-none\"></i> <span class=\"d-none d-lg-block\">Oui</span></button>\n");
      out.write("                    </fieldset>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/js/vendors.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/core/app-menu.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/core/app.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/scripts/customizer.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/scripts/footer.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/mask.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/datatable.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("                            function numberMask(inputid, limit) {\n");
      out.write("                                return IMask(\n");
      out.write("                                        document.getElementById(inputid),\n");
      out.write("                                        {\n");
      out.write("                                            mask: '$ num',\n");
      out.write("                                            blocks: {\n");
      out.write("                                                num: {\n");
      out.write("                                                    mask: Number,\n");
      out.write("                                                    thousandsSeparator: ' ',\n");
      out.write("                                                    min: 1,\n");
      out.write("                                                    max: limit\n");
      out.write("                                                }\n");
      out.write("                                            }\n");
      out.write("                                        }\n");
      out.write("                                );\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function readable(nbr){\n");
      out.write("                                var nombre = '' + nbr;\n");
      out.write("                                var retour = '';\n");
      out.write("                                var count = 0;\n");
      out.write("                                for (var i = nombre.length - 1; i >= 0; i--)\n");
      out.write("                                {\n");
      out.write("                                    if (count != 0 && count % 3 == 0)\n");
      out.write("                                        retour = nombre[i] + ' ' + retour;\n");
      out.write("                                    else\n");
      out.write("                                        retour = nombre[i] + retour;\n");
      out.write("                                    count++;\n");
      out.write("                                }\n");
      out.write("                                return retour;\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function disconnect() {\n");
      out.write("                                window.location.href = \"deconnexion\";\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" != null && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length > 0) {\n");
      out.write("                                $(\"#tableaudebord\").attr(\"class\", $(\"#tableaudebord\").attr(\"class\").replace(\" active\", \"\"));\n");
      out.write("                                $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\", $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\") + \" active\");\n");
      out.write("                            } else {\n");
      out.write("                                $(\"#tableaudebord\").attr(\"class\", $(\"#tableaudebord\").attr(\"class\") + \" active\");\n");
      out.write("                                $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\", $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").attr(\"class\").replace(\" active\", \"\"));\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function resetData() {\n");
      out.write("                                $(\"#add_form\")[0].reset();\n");
      out.write("                                $(\"#edit_form\")[0].reset();\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function holdModal(id) {\n");
      out.write("                                $(\"#\" + id).modal({\n");
      out.write("                                    keyboard: false,\n");
      out.write("                                    backdrop: 'static'\n");
      out.write("                                }).show();\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function removeSession(parameter) {\n");
      out.write("                                $.ajax({\n");
      out.write("                                    url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/services/removeSession.jsp',\n");
      out.write("                                    type: \"POST\",\n");
      out.write("                                    data: {parameter: parameter},\n");
      out.write("                                    dataType: 'json',\n");
      out.write("                                    success: function (data) {\n");
      out.write("                                    },\n");
      out.write("                                    error: function (data) {\n");
      out.write("                                        toastr.error(data.message, \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME().toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active_menu.toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \");\n");
      out.write("                                    }\n");
      out.write("                                });\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/js/extensions/toastr.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/vendors/js/charts/chart.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("    $(window).on(\"load\",\n");
      out.write("            (function () {\n");
      out.write("                Chart.defaults.derivedLine = Chart.defaults.line;\n");
      out.write("                var t = Chart.controllers.line.prototype.draw,\n");
      out.write("                        e = Chart.controllers.line.extend(\n");
      out.write("                                {draw: function () {\n");
      out.write("                                        t.apply(this, arguments);\n");
      out.write("                                        var e = this.chart.chart.ctx, o = e.stroke;\n");
      out.write("                                        e.stroke = function () {\n");
      out.write("                                            e.save(),\n");
      out.write("                                                    e.shadowColor = \"#ffb6c0\",\n");
      out.write("                                                    e.shadowBlur = 30,\n");
      out.write("                                                    e.shadowOffsetX = 0,\n");
      out.write("                                                    e.shadowOffsetY = 20,\n");
      out.write("                                                    o.apply(this, arguments),\n");
      out.write("                                                    e.restore()\n");
      out.write("                                        }\n");
      out.write("                                    }});\n");
      out.write("\n");
      out.write("                Chart.controllers.derivedLine = e;\n");
      out.write("                var o = document.querySelector(\"#thisYearRevenue\").getContext(\"2d\"),\n");
      out.write("                        a = (new Chart(o, {type: \"derivedLine\",\n");
      out.write("                            data: {labels: [\"Lun\", \"Mar\", \"Mer\", \"Jeu\", \"Ven\", \"Sam\", \"Dim\", \"Lun\"],\n");
      out.write("                                datasets: [{data: [5e3, 1e4, 4e3, 14500, 8e3, 18500, 8e3, 2e4],\n");
      out.write("                                        borderWidth: 4,\n");
      out.write("                                        borderColor: \"#FF4961\",\n");
      out.write("                                        pointBackgroundColor: \"#FFF\",\n");
      out.write("                                        pointBorderColor: \"#FF4961\",\n");
      out.write("                                        pointHoverBackgroundColor: \"#FFF\",\n");
      out.write("                                        pointHoverBorderColor: \"#FF4961\",\n");
      out.write("                                        pointRadius: 0,\n");
      out.write("                                        pointHoverRadius: 6, fill: !1}]},\n");
      out.write("                            options: {responsive: !0,\n");
      out.write("                                tooltips: {displayColors: !1,\n");
      out.write("                                    callbacks: {\n");
      out.write("                                        label: function (t, e) {},\n");
      out.write("                                        title: function () {}}},\n");
      out.write("                                legend: {display: !1}, scales: {\n");
      out.write("                                    xAxes: [{gridLines: {display: !1}}],\n");
      out.write("                                    yAxes: [{ticks: {padding: 10, stepSize: 5e3, max: 2e4, min: 0},\n");
      out.write("                                            gridLines: {display: !0, drawBorder: !1, lineWidth: 1, color: \"#e9ebf5\"}}]}}}),\n");
      out.write("                                document.querySelector(\"#lastYearRevenue\").getContext(\"2d\"));\n");
      out.write("                new Chart(a, {type: \"line\",\n");
      out.write("                    data: {labels: [\"Lun\", \"Mar\", \"Mer\", \"Jeu\", \"Ven\", \"Sam\", \"Dim\", \"Lun\"],\n");
      out.write("                        datasets: [{data: [7e3, 15e3, 6e3, 10500, 3e3, 11500, 4e3, 1e4],\n");
      out.write("                                borderWidth: 4, borderDash: [8, 4],\n");
      out.write("                                borderColor: \"#c3c3c3\",\n");
      out.write("                                pointBackgroundColor: \"#FFF\",\n");
      out.write("                                pointBorderColor: \"#c3c3c3\",\n");
      out.write("                                pointHoverBackgroundColor: \"#FFF\",\n");
      out.write("                                pointHoverBorderColor: \"#c3c3c3\",\n");
      out.write("                                pointRadius: 0, pointHoverRadius: 6, fill: !1}]},\n");
      out.write("                    options: {responsive: !0\n");
      out.write("                        , tooltips: {displayColors: !1,\n");
      out.write("                            callbacks: {label: function (t, e) {},\n");
      out.write("                                title: function () {}}},\n");
      out.write("                        legend: {display: !1}, scales: {\n");
      out.write("                            xAxes: [{gridLines: {display: !1}}],\n");
      out.write("                            yAxes: [{ticks: {padding: 10,\n");
      out.write("                                        stepSize: 5e3, max: 2e4, min: 0},\n");
      out.write("                                    gridLines: {display: !0, drawBorder: !1, zeroLineColor: \"#e5e5e5\"}}]}}});\n");
      out.write("                Chart.defaults.hitRateDoughnut = Chart.defaults.doughnut;\n");
      out.write("                t = Chart.controllers.doughnut.prototype.draw;\n");
      out.write("                var r = Chart.controllers.doughnut.extend({draw: function () {\n");
      out.write("                        t.apply(this, arguments);\n");
      out.write("                        var e = this.chart.chart.ctx, o = e.fill,\n");
      out.write("                                a = this.chart.width, r = this.chart.height, i = (r / 114).toFixed(2);\n");
      out.write("                        this.chart.ctx.font = i + \"em Verdana\", this.chart.ctx.textBaseline = \"middle\";\n");
      out.write("\n");
      out.write("                        var l = \"");
      out.print(pvfree);
      out.write("%\", n = Math.round((a - this.chart.ctx.measureText(l).width) / 2),\n");
      out.write("                                d = r / 2;\n");
      out.write("                        this.chart.ctx.fillStyle = \"#28D094\", \"rtl\" == $(\"html\").data(\"textdirection\") && (n = Math.round((a - this.chart.ctx.measureText(l).width) / 1.15)),\n");
      out.write("                                this.chart.ctx.fillText(l, n, d),\n");
      out.write("                                e.fill = function () {\n");
      out.write("                                    e.save(), e.shadowColor = \"#bbbbbb\", e.shadowBlur = 30,\n");
      out.write("                                            e.shadowOffsetX = 0, e.shadowOffsetY = 12, o.apply(this, arguments), e.restore()\n");
      out.write("                                }\n");
      out.write("                    }});\n");
      out.write("                var pvfree = \"");
      out.print(pvfree);
      out.write("\"\n");
      out.write("                Chart.controllers.hitRateDoughnut = r;\n");
      out.write("                o = document.getElementById(\"hit-rate-doughnut\"),\n");
      out.write("                        new Chart(o, {type: \"hitRateDoughnut\", data: {labels: [\"Pourcentage de vehicules libres\", \"Poucentage de vehicules non-libres\"],\n");
      out.write("                                datasets: [{label: \"Favourite\", backgroundColor: [\"#28D094\", \"#FF4961\"], data: [pvfree, 100 - pvfree]}]},\n");
      out.write("                            options: {responsive: !0, title: {display: !1}, legend: {display: !1},\n");
      out.write("                                layout: {padding: {left: 16, right: 16, top: 16, bottom: 16}},\n");
      out.write("                                cutoutPercentage: 62, animation: {animateScale: !1, duration: 2500}}});\n");
      out.write("                Chart.defaults.dealsDoughnut = Chart.defaults.doughnut;\n");
      out.write("                t = Chart.controllers.doughnut.prototype.draw;\n");
      out.write("                var i = Chart.controllers.doughnut.extend({draw: function () {\n");
      out.write("                        t.apply(this, arguments);\n");
      out.write("                        var e = this.chart.chart.ctx, o = e.fill, a = this.chart.width,\n");
      out.write("                                r = this.chart.height, i = (r / 114).toFixed(2);\n");
      out.write("                        this.chart.ctx.font = i + \"em Verdana\", this.chart.ctx.textBaseline = \"middle\";\n");
      out.write("                        var l = \"");
      out.print(pvprogress);
      out.write("%\", n = Math.round((a - this.chart.ctx.measureText(l).width) / 2), d = r / 2;\n");
      out.write("                        this.chart.ctx.fillStyle = \"#fff\", \"rtl\" == $(\"html\").data(\"textdirection\") && (n = Math.round((a - this.chart.ctx.measureText(l).width) / 1.15)), this.chart.ctx.fillText(l, n, d), e.fill = function () {\n");
      out.write("                            e.save(), e.shadowColor = \"#FF4961\", e.shadowBlur = 30, e.shadowOffsetX = 0, e.shadowOffsetY = 12, o.apply(this, arguments), e.restore()\n");
      out.write("                        }\n");
      out.write("                    }});\n");
      out.write("                Chart.controllers.dealsDoughnut = i;\n");
      out.write("                o = document.getElementById(\"deals-doughnut\"),\n");
      out.write("                        new Chart(o, {type: \"dealsDoughnut\",\n");
      out.write("                            data: {labels: [\"Pourcentage de location en cours\", \"Pourcentage de location annulee/retard\"], color: \"#fff\",\n");
      out.write("                                datasets: [{label: \"Favourite\", borderWidth: 0, backgroundColor: [\"#FFF\", \"#ff7b8c\"], data: [");
      out.print(new D_Location().get().size()==0?0: 100 - pvprogress);
      out.write(',');
      out.write(' ');
      out.print(pvprogress);
      out.write(", ]}]},\n");
      out.write("                            options: {responsive: !0, title: {display: !1}, legend: {display: !1},\n");
      out.write("                                elements: {}, layout: {padding: {left: 16, right: 16, top: 16, bottom: 16}},\n");
      out.write("                                cutoutPercentage: 62, animation: {animateScale: !1, duration: 5e3}}});\n");
      out.write("                var l = document.getElementById(\"earning-chart\").getContext(\"2d\");\n");
      out.write("                new Chart(l, {type: \"line\", options: {responsive: !0, maintainAspectRatio: !1, datasetStrokeWidth: 3, pointDotStrokeWidth: 4, tooltipFillColor: \"rgba(0,0,0,0.8)\", legend: {display: !1, position: \"bottom\"}, hover: {mode: \"label\"}, scales: {xAxes: [{display: !1}], yAxes: [{display: !1, ticks: {min: 0, max: 70}}]}, title: {display: !1, fontColor: \"#FFF\", fullWidth: !1, fontSize: 40, text: \"82%\"}}, data: {labels: [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\"],\n");
      out.write("                        datasets: [{label: \"My First dataset\", data: [28, 35, 36, 48, 46, 42, 60], backgroundColor: \"rgba(255,117,136,0.12)\", borderColor: \"#FF4961\", borderWidth: 3, strokeColor: \"#FF4961\", capBezierPoints: !0, pointColor: \"#fff\", pointBorderColor: \"#FF4961\", pointBackgroundColor: \"#FFF\", pointBorderWidth: 3, pointRadius: 5, pointHoverBackgroundColor: \"#FFF\", pointHoverBorderColor: \"#FF4961\", pointHoverRadius: 7}]}});\n");
      out.write("                $(\"#world-map-markers\").vectorMap({map: \"world_mill\", backgroundColor: \"#fff\", zoomOnScroll: !1,\n");
      out.write("                    series: {regions: [{values: visitorData, scale: [\"rgb(212,0,42)\", \"#fdd6db\"], normalizeFunction: \"polynomial\"}]},\n");
      out.write("                    onRegionTipShow: function (t, e, o) {\n");
      out.write("                        e.html(e.html() + \" (Visitor - \" + visitorData[o] + \")\")\n");
      out.write("                    }}), Morris.Donut({element: \"sessions-browser-donut-chart\", data: [{label: \"Chrome\", value: 3500}, {label: \"Firefox\", value: 2500}, {label: \"Safari\", value: 2e3}, {label: \"Opera\", value: 1e3}, {label: \"Internet Explorer\", value: 500}], resize: !0, colors: [\"#40C7CA\", \"#FF7588\", \"#2DCEE3\", \"#FFA87D\", \"#16D39A\"]})\n");
      out.write("            }));\n");
      out.write("\n");
      out.write("    if (\"");
      out.print(request.getSession().getAttribute("welcome"));
      out.write("\" != \"null\") {\n");
      out.write("        toastr.info(\"");
      out.print(request.getSession().getAttribute("welcome"));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.getCOMPANYNAME().toUpperCase()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" - TABLEAU DE BORD\");\n");
      out.write("        removeSession(\"welcome\");\n");
      out.write("    }\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
